name: Hello World
on: 
  - push
  - workflow_dispatch
jobs:
  Hello-World-Job:
    runs-on: codebuild-codebuild-ghr-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"